project:
  type: website
  output-dir: docs

website:
  title: "Chris' Website"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

  page-footer:
      background: light
      left: Copyright 2025, Chris Rooney
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

